export const USER_FETCH_REQUESTED = '@task/USER_FETCH_REQUESTED'
export const USER_FETCH_FAILED = '@task/USER_FETCH_FAILED'
export const ADD_TASK = '@task/ADD_TASK'
export const REMOVE_TASK_BY_ID = '@task/REMOVE_TASK_BY_ID'
export const GET_DATA = '@task/GET_DATA'
export const GET_DATA_SUCCESS = '@task/GET_DATA_SUCCESS'
export const GET_DATA_FAILED = '@task/GET_DATA_FAILED'